INSERT INTO genre (genreid, name) VALUES
 (1, 'Abstract Strategy'),
 (2, 'Action / Dexterity'),
 (3, 'Adventure'),
 (4, 'Age of Reason'),
 (5, 'American Civil War'),
 (6, 'American Indian Wars'),
 (7, 'American Revolutionary War'),
 (8, 'American West'),
 (9, 'Ancient'),
 (10, 'Animals'),
 (11, 'Arabian'),
 (12, 'Aviation / Flight'),
 (13, 'Bluffing'),
 (14, 'Book'),
 (15, 'Card Game'),
 (16, 'Children''s Game'),
 (17, 'City Building'),
 (18, 'Civil War'),
 (19, 'Civilization'),
 (20, 'Collectible Components'),
 (21, 'Comic Book / Strip'),
 (22, 'Deduction'),
 (23, 'Dice'),
 (24, 'Economic'),
 (25, 'Educational'),
 (26, 'Electronic'),
 (27, 'Environmental'),
 (28, 'Expansion for Base-game'),
 (29, 'Exploration'),
 (30, 'Fan Expansion'),
 (31, 'Fantasy'),
 (32, 'Farming'),
 (33, 'Fighting'),
 (34, 'Game System'),
 (35, 'Horror'),
 (36, 'Humor'),
 (37, 'Industry / Manufacturing'),
 (38, 'Korean War'),
 (39, 'Mafia'),
 (40, 'Math'),
 (41, 'Mature / Adult'),
 (42, 'Maze'),
 (43, 'Medical'),
 (44, 'Medieval'),
 (45, 'Memory'),
 (46, 'Miniatures'),
 (47, 'Modern Warfare'),
 (48, 'Movies / TV / Radio theme'),
 (49, 'Murder / Mystery'),
 (50, 'Music'),
 (51, 'Mythology'),
 (52, 'Napoleonic'),
 (53, 'Nautical'),
 (54, 'Negotiation'),
 (55, 'Novel-based'),
 (56, 'Number'),
 (57, 'Party Game'),
 (58, 'Pike and Shot'),
 (59, 'Pirates'),
 (60, 'Political'),
 (61, 'Post-Napoleonic'),
 (62, 'Prehistoric'),
 (63, 'Print & Play'),
 (64, 'Puzzle'),
 (65, 'Racing'),
 (66, 'Real-time'),
 (67, 'Religious'),
 (68, 'Renaissance'),
 (69, 'Science Fiction'),
 (70, 'Space Exploration'),
 (71, 'Spies / Secret Agents'),
 (72, 'Sports'),
 (73, 'Territory Building'),
 (74, 'Third-party Expansion'),
 (75, 'Trains'),
 (76, 'Transportation'),
 (77, 'Travel'),
 (78, 'Trivia'),
 (79, 'Video Game Theme'),
 (80, 'Vietnam War'),
 (81, 'Wargame'),
 (82, 'Word Game'),
 (83, 'World War I'),
 (84, 'World War II'),
 (85, 'Zombies');
