INSERT INTO mechanic (mechanicid, name) VALUES
(1, 'Chaining'),
(2, 'End Game Bonuses'),
(3, 'Hand Management'),
(4, 'Income'),
(5, 'Loans'),
(6, 'Market'),
(7, 'Multi-Use Cards'),
(8, 'Network and Route Building'),
(9, 'Ownership'),
(10, 'Tags'),
(11, 'Tech Trees / Tech Tracks'),
(12, 'Tile Placement'),
(13, 'Turn Order: Stat-Based'),
(14, 'Variable Set-up'),
(15, 'Action Points'),
(16, 'Cooperative Game'),
(17, 'Legacy Game'),
(18, 'Point to Point Movement'),
(19, 'Scenario / Mission / Campaign Game'),
(20, 'Set Collection'),
(21, 'Trading'),
(22, 'Variable Player Powers'),
(23, 'Contracts'),
(24, 'Events'),
(25, 'Grid Coverage'),
(26, 'Hexagon Grid'),
(27, 'Increase Value of Unchosen Resources'),
(28, 'Open Drafting'),
(29, 'Race'),
(30, 'Solo / Solitaire Game'),
(31, 'Track Movement'),
(32, 'Action Queue'),
(33, 'Action Retrieval'),
(34, 'Campaign / Battle Card Driven'),
(35, 'Card Play Conflict Resolution'),
(36, 'Communication Limits'),
(37, 'Critical Hits and Failures'),
(38, 'Deck Construction'),
(39, 'Grid Movement'),
(40, 'Line of Sight'),
(41, 'Modular Board'),
(42, 'Narrative Choice / Paragraph'),
(43, 'Once-Per-Game Abilities'),
(44, 'Role Playing'),
(45, 'Simultaneous Action Selection'),
(46, 'Storytelling'),
(47, 'Action Drafting'),
(48, 'Area-Impulse'),
(49, 'Dice Rolling'),
(50, 'Follow'),
(51, 'King of the Hill'),
(52, 'Movement Points'),
(53, 'Variable Phase Order'),
(54, 'Voting'),
(55, 'Deck, Bag, and Pool Building'),
(56, 'Delayed Purchase'),
(57, 'Force Commitment'),
(58, 'Take That'),
(59, 'Turn Order: Progressive'),
(60, 'Worker Placement'),
(61, 'Closed Drafting'),
(62, 'Area Majority / Influence'),
(63, 'Area Movement'),
(64, 'Team-Based Game'),
(65, 'Die Icon Resolution'),
(66, 'Hidden Movement'),
(67, 'Worker Placement, Different Worker Types'),
(68, 'Automatic Resource Growth'),
(69, 'Player Elimination'),
(70, 'Turn Order: Pass Order'),
(71, 'Victory Points as a Resource'),
(72, 'Action / Event'),
(73, 'Advantage Token'),
(74, 'Simulation'),
(75, 'Sudden Death Ending'),
(76, 'Tug of War'),
(77, 'Auction / Bidding'),
(78, 'Auction: Dutch'),
(79, 'Pattern Building'),
(80, 'Alliances'),
(81, 'Hot Potato'),
(82, 'Passed Action Token'),
(83, 'Zone of Control'),
(84, 'Melding and Splaying'),
(85, 'Score-and-Reset Game'),
(86, 'Hidden Roles'),
(87, 'Interrupts'),
(88, 'Semi-Cooperative Game'),
(89, 'Traitor Game'),
(90, 'Map Addition'),
(91, 'Pick-up and Deliver'),
(92, 'Push Your Luck'),
(93, 'Enclosure'),
(94, 'Layering'),
(95, 'Pattern Recognition'),
(96, 'Square Grid'),
(97, 'Hidden Victory Points'),
(98, 'Investment'),
(99, 'Resource to Move'),
(100, 'Map Deformation'),
(101, 'Stat Check Resolution'),
(102, 'Negotiation'),
(103, 'Relative Movement'),
(104, 'Turn Order: Role Order'),
(105, 'Worker Placement with Dice Workers'),
(106, 'Kill Steal'),
(107, 'Turn Order: Claim Action'),
(108, 'Deduction'),
(109, 'Trick-taking'),
(110, 'Turn Order: Auction'),
(111, 'Roles with Asymmetric Information'),
(112, 'Catch the Leader'),
(113, 'Programmed Movement'),
(114, 'Flicking'),
(115, 'Bribery'),
(116, 'Moving Multiple Units'),
(117, 'Map Reduction'),
(118, 'Memory'),
(119, 'Bias'),
(120, 'Auction: Turn Order Until Pass'),
(121, 'Neighbor Scope'),
(122, 'Connections'),
(123, 'Commodity Speculation'),
(124, 'Stock Holding'),
(125, 'Secret Unit Deployment'),
(126, 'Resource Queue'),
(127, 'Paper-and-Pencil'),
(128, 'Betting and Bluffing'),
(129, 'Prisoner''s Dilemma'),
(130, 'Rock-Paper-Scissors'),
(131, 'Constrained Bidding'),
(132, 'Mancala'),
(133, 'Highest-Lowest Scoring'),
(134, 'Chit-Pull System'),
(135, 'Selection Order Bid'),
(136, 'Ladder Climbing'),
(137, 'Rondel'),
(138, 'Command Cards'),
(139, 'Turn Order: Time Track'),
(140, 'Targeted Clues'),
(141, 'Static Capture'),
(142, 'Auction: Once Around'),
(143, 'Closed Economy Auction'),
(144, 'Auction: Fixed Placement'),
(145, 'Auction: Multiple Lot'),
(146, 'Slide / Push'),
(147, 'Auction: Sealed Bid'),
(148, 'Order Counters'),
(149, 'Minimap Resolution'),
(150, 'Bingo'),
(151, 'Three Dimensional Movement'),
(152, 'Roll / Spin and Move'),
(153, 'Movement Template'),
(154, 'Re-rolling and Locking'),
(155, 'Predictive Bid'),
(156, 'Multiple Maps'),
(157, 'Auction: English'),
(158, 'Random Production'),
(159, 'I Cut, You Choose'),
(160, 'Finale Ending'),
(161, 'Line Drawing'),
(162, 'Real-Time'),
(163, 'Acting'),
(164, 'Singing'),
(165, 'Cube Tower'),
(166, 'Pattern Movement'),
(167, 'Pieces as Map'),
(168, 'Move Through Deck'),
(169, 'Drawing'),
(170, 'Ordering'),
(171, 'Bids As Wagers'),
(172, 'Elapsed Real Time Ending'),
(173, 'Auction Compensation'),
(174, 'Questions and Answers'),
(175, 'Turn Order: Random'),
(176, 'Lose a Turn'),
(177, 'Ratio / Combat Results Table'),
(178, 'Auction: Dutch Priority'),
(179, 'Matching'),
(180, 'Stacking and Balancing'),
(181, 'Spelling'),
(182, 'Different Dice Movement'),
(183, 'Crayon Rail System'),
(184, 'Player Judge'),
(185, 'Physical Removal'),
(186, 'Measurement Movement'),
(187, 'Single Loser Game'),
(188, 'Action Timer'),
(189, 'Induction'),
(190, 'Speed Matching');
